using System.Globalization;

namespace HarmonicaPlayer;

// 界面语言：中文（默认，保持既有中文文案与测试基线）与英文。
public enum UiLanguage { Chinese, English }

// 语言偏好的单一来源：设置文件里存 zh / en。无法识别的值一律按中文处理，
// 与 ThemePreference 一样：非法值只影响这一个字段，不会让整份设置失效。
public static class LanguagePreference
{
    public static UiLanguage Parse(string? value) => value?.Trim().ToLowerInvariant() switch
    {
        "en" or "en-us" or "english" => UiLanguage.English,
        _ => UiLanguage.Chinese
    };

    public static string Serialize(UiLanguage language) => language == UiLanguage.English ? "en" : "zh";
}

// 轻量本地化：以“中文原文”为键查英文表，查不到就原样返回中文。
// 这样默认中文的输出与改动前逐字一致（既有测试断言不受影响），
// 而且以后补翻译只需要往表里加一行，不用改调用点。
public static class Loc
{
    public static UiLanguage Current { get; private set; } = UiLanguage.Chinese;
    public static bool IsEnglish => Current == UiLanguage.English;
    public static void SetLanguage(UiLanguage value) => Current = value;
    public static void Reset() => Current = UiLanguage.Chinese;

    // 已翻译条目数：测试与自检用，界面不显示。
    public static int EntryCount => English.Count;

    public static string T(string chinese) =>
        IsEnglish && English.TryGetValue(chinese, out string? english) ? english : chinese;

    // 带参数的文案：模板里的 {0} {1} 与 string.Format 一致，中文模板本身保持原样。
    public static string F(string chinese, params object?[] arguments) =>
        string.Format(CultureInfo.InvariantCulture, T(chinese), arguments);

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        // ---------- 外壳：标题栏 / 选项卡 / 状态 ----------
        { "外观主题：", "Theme:" },
        { "跟随系统", "Follow system" },
        { "浅色", "Light" },
        { "深色", "Dark" },
        { "外观主题。选择后立即生效并记住；“跟随系统”会实时响应 Windows 个性化设置。",
          "Interface theme. Applies immediately and is remembered; \"Follow system\" tracks Windows personalization live." },
        { "界面语言：", "Language:" },
        { "界面语言。切换后立即生效并记住；尚未翻译的条目会保持中文。",
          "Interface language. Applies immediately and is remembered; entries that are not translated yet stay in Chinese." },
        { "最小化", "Minimize" },
        { "最大化/还原", "Maximize / restore" },
        { "关闭", "Close" },
        { "拖动标题栏或空白处可移动窗口；双击标题栏最大化或还原。",
          "Drag the title bar or empty space to move; double-click the title bar to maximize or restore." },
        { "中文界面。", "Chinese interface." },
        { "English interface.", "English interface." },
        { "界面语言已切换为中文。", "Interface language switched to Chinese." },
        { "界面语言已切换为英文。", "Interface language switched to English." },
        { "TXT → 单音口琴演奏", "TXT → single-note harmonica play" },
        { "曲谱库", "Score library" },
        { "试听与预览", "Preview & listen" },
        { "编辑与演奏", "Editor & performance" },
        { "快捷键与日志", "Hotkeys & log" },

        // ---------- 主窗口：字段与按钮 ----------
        { "未命名曲谱", "Untitled score" },
        { "尚未保存", "Not saved yet" },
        { "保存 TXT", "Save TXT" },
        { "另存为", "Save as" },
        { "新建", "New" },
        { "仅测试（不会操作游戏）", "Test only (no game input)" },
        { "就绪：先导入谱面，快捷键状态见上方。", "Ready: import a score first; hotkey status is shown above." },
        { "导入 TXT", "Import TXT" },
        { "导入单旋律 MIDI", "Import single-line MIDI" },
        { "预览 / 检查", "Preview / check" },
        { "定位曲谱错误", "Locate score error" },
        { "自定义快捷键", "Custom hotkeys" },
        { "重试注册", "Retry registration" },
        { "修改快捷键", "Change hotkeys" },
        { "清除上次操作提示", "Dismiss last message" },
        { "开始演奏 ", "Start playing " },
        { "开始测试 ", "Start test " },
        { "停止 ", "Stop " },
        { "曲名（与文件名独立）：", "Title (independent of the file name):" },
        { "速度（BPM）：", "Tempo (BPM):" },
        { "音符间隔／留白(ms)：", "Note gap (ms):" },
        { "【高音】 （低音） 【【1】】最高do、【【#1】】升半音；5:1.25指定总拍数；#或＃升半音；0休止，-或—延长一拍，_半拍，__四分之一拍，.附点。例：1 2_ 3_ 5 — | 0 6. 5_ 1 |",
          "[high] (low) [[1]] top do, [[#1]] top do sharp; 5:1.25 sets total beats; # or ＃ = sharp; 0 = rest, - or — = one beat longer, _ = half beat, __ = quarter beat, . = dotted. E.g. 1 2_ 3_ 5 — | 0 6. 5_ 1 |" },

        // ---------- 主窗口：卡片与说明 ----------
        { "本地试听（不发送游戏按键）", "Local preview (no game input)" },
        { "解析预览", "Parse preview" },
        { "全局快捷键与设置", "Global hotkeys & settings" },
        { "演奏日志", "Play log" },
        { "每个音的拍数与时间；不是图片识谱。", "Beats and timing of every note; this is not image recognition." },
        { "开始/停止键可自定义；修改期间会暂停全局快捷键，关闭此窗口后重新注册。",
          "The start/stop keys are configurable; global hotkeys pause while editing and are re-registered after the dialog closes." },
        { "游戏演奏模式会操作键鼠；仅测试不会操作游戏，也不会发声。开始后倒计时3秒，请切到游戏口琴界面；演奏期间除停止键外不要操作键鼠。",
          "Game performance mode sends keyboard and mouse input; test-only mode neither touches the game nor plays sound. After starting there is a 3-second countdown, so switch to the in-game harmonica view first; during playback do not touch the keyboard or mouse except the stop key." },

        // ---------- 顶部提示与状态 ----------
        { "无法开始：请先修正曲谱或速度、音符间隔。", "Cannot start: fix the score, tempo or note gap first." },
        { "无法开始游戏演奏：请先修复停止快捷键。", "Cannot start game performance: fix the stop hotkey first." },
        { "权限提醒：当前未以管理员身份运行；若游戏权限更高，可能无法操作游戏。可继续演奏，必要时以管理员身份运行播放器。",
          "Permission notice: HarpKit is not running as administrator; if the game runs with higher privileges it may ignore the input. You can keep playing, or restart HarpKit as administrator if needed." },
        { "当前为仅测试：不会操作游戏，也不会发声；需要声音请使用本地试听。",
          "Test-only mode: no game input and no sound; use local preview when you want to hear it." },
        { "权限提醒：未以管理员运行，允许继续。\n", "Permission notice: not running as administrator, continuing.\n" },
        { "权限：", "Permission: " },
        { "已以管理员身份运行", "running as administrator" },
        { "未以管理员身份运行", "not running as administrator" },
        { "　|　当前模式：", "  |  Mode: " },
        { "仅测试", "test only" },
        { "游戏演奏", "game performance" },

        // ---------- 曲谱库 ----------
        { "曲谱库：每首曲子可以绑一个自己的快捷键", "Score library: one hotkey per score" },
        { "添加常弹的 TXT 曲谱，再为每首绑定一个全局快捷键：在游戏里按一下就会加载并演奏。曲谱快捷键与开始/停止键共用同一套注册，冲突时会明确提示。",
          "Add the TXT scores you play often and bind a global hotkey to each one: pressing it in game loads and plays that score. Library hotkeys share the same registration as start/stop, so conflicts are reported clearly." },
        { "添加曲谱…", "Add score…" },
        { "绑定快捷键…", "Bind hotkey…" },
        { "清除绑定", "Clear binding" },
        { "移除", "Remove" },
        { "上移", "Move up" },
        { "下移", "Move down" },
        { "加载到编辑器", "Load into editor" },
        { "加载并演奏", "Load and play" },
        { "按快捷键立即演奏（不勾选则只加载曲谱）", "Play on hotkey (unchecked: only load the score)" },
        { "（当前）", " (current)" },
        { "未绑定", "Unbound" },
        { "未绑定快捷键", "No hotkey" },
        { "文件不存在", "File missing" },
        { "待注册", "Pending" },
        { "还没有曲谱：点“添加曲谱…”把常弹的 TXT 加进来，再为它绑定快捷键。",
          "No scores yet: click \"Add score…\" to add the TXT files you play often, then bind a hotkey to each one." },
        { "曲谱库为空：添加曲谱后可以为每首绑定一个全局快捷键。",
          "The score library is empty: add scores and bind a global hotkey to each of them." },
        { "共{0}首，已绑定{1}个曲谱快捷键", "{0} score(s), {1} library hotkey(s) bound" },
        { "，{0}首文件不存在（请重新添加或移除）", ", {0} file(s) missing (re-add or remove them)" },
        { "。快捷键被其他程序占用时只影响这一首，其他曲谱不受影响。",
          ". If a hotkey is taken by another program only that score is affected." },
        { "\n当前选中：", "\nSelected: " },
        { "正在演奏，曲谱库暂不可修改；请先按停止键，再添加、移除或改绑定。",
          "Playback is running, so the library is locked; press the stop key first, then add, remove or rebind." },
        { "曲谱库快捷键：按下后加载并演奏（倒计时3秒，随时可用停止键取消）。",
          "Library hotkey: loads and plays the score (3-second countdown, stop key cancels at any time)." },
        { "曲谱库快捷键：只把曲谱加载到编辑器，不自动演奏。",
          "Library hotkey: only loads the score into the editor without playing." },
        { "没有新增曲谱：所选文件已在列表中，或曲谱库已达上限（{0}首）。",
          "Nothing added: the selected files are already listed, or the library reached its limit ({0} scores)." },
        { "已添加{0}首曲谱", "{0} score(s) added" },
        { "，跳过{1}个（重复或超过上限）", ", {1} skipped (duplicate or over the limit)" },
        { "。选中一行后点“绑定快捷键…”设置按键。", ". Select a row and click \"Bind hotkey…\" to set its key." },
        { "已从曲谱库移除“{0}”（曲谱文件与编辑器内容未改动）。",
          "Removed \"{0}\" from the library (the file and the editor are untouched)." },
        { "无法打开文件选择框：", "Cannot open the file picker: " },
        { "加载曲谱库曲谱失败：", "Failed to load the library score: " },
        { "“{0}”已绑定 {1}：", "\"{0}\" is now bound to {1}: " },
        { "已清除“{0}”的曲谱快捷键。", "Cleared the library hotkey of \"{0}\"." },
        { "正在演奏或读写曲谱，本次曲谱库快捷键未生效。",
          "Playback or a score operation is running, so this library hotkey did nothing." },
        { "曲谱库“{0}”的文件不存在：{1}\n请重新添加这首曲谱，或从曲谱库移除。",
          "The file of \"{0}\" is missing: {1}\nAdd this score again or remove it from the library." },
        { "当前曲谱有未保存的修改，已取消曲谱库切换（“{0}”）。请先在播放器中保存或新建，再使用曲谱库快捷键。",
          "The current score has unsaved changes, so switching to \"{0}\" was cancelled. Save or start a new score in HarpKit first, then use the library hotkey." },
        { "已从曲谱库加载“{0}”。", "Loaded \"{0}\" from the score library." },
        { "已加载曲谱，请先修正顶部提示的错误再演奏。",
          "Score loaded; fix the errors shown above before playing." },
        { "曲谱库尚未绑定快捷键。", "No library hotkey is bound yet." },
        { "“{0}”{1}", "\"{0}\" {1}" },
        { "曲谱库 {0} 个快捷键已就绪。", "{0} library hotkey(s) ready." },
        { "曲谱库快捷键未生效：{0}。", "Library hotkey(s) not active: {0}." },
        { "、", ", " },
        { "为曲谱绑定快捷键", "Bind a hotkey to a score" },
        { "曲谱：{0}\n绑定后无论在哪个窗口，按这个键都会加载并演奏这首曲子。它与开始/停止键共用同一套注册，被其他程序占用时会明确提示。",
          "Score: {0}\nOnce bound, this key loads and plays the score from any window. It shares the same registration as start/stop, so conflicts with other programs are reported clearly." },
        { "曲谱快捷键", "Library hotkey" },
        { "停止键始终优先保留；演奏键 Z/X/C/V/B/N/M/逗号与 F12、Win 组合不能作为曲谱快捷键。",
          "The stop key always wins; the performance keys Z/X/C/V/B/N/M/comma, F12 and Win combinations cannot be used as library hotkeys." },
        { "取消", "Cancel" },
        { "确定", "OK" },

        // ---------- 试听与导出 ----------
        { "从头试听", "Preview from start" },
        { "从光标试听", "Preview from cursor" },
        { "导出 MIDI", "Export MIDI" },
        { "试听音量：", "Preview volume:" },
        { "本地试听：Special 20 真实口琴采样，不发送游戏按键。",
          "Local preview: real Special 20 harmonica samples, no game input." },
        { "本地试听中；点击停止或按停止快捷键结束。", "Previewing; click Stop or press the stop hotkey to end it." },
        { "{0}/{1}：{2} · 已试听 {3} / {4} · 剩余 {5}", "{0}/{1}: {2} · played {3} / {4} · remaining {5}" },
        { "试听完成 · 本段 {0}", "Preview finished · this section {0}" },
        { "试听完成，可继续编辑或导出 MIDI。", "Preview finished; keep editing or export MIDI." },
        { "试听已停止，可继续编辑。", "Preview stopped; you can keep editing." },
        { "无法试听，请查看顶部提示。", "Cannot preview; see the notice above." },
        { "试听失败，可修正后重试。", "Preview failed; fix the score and try again." },
        { "已导出整首曲谱为单音轨 MIDI（含BPM、休止和间隔）；TXT保存状态不变。",
          "Exported the whole score as a single-track MIDI (BPM, rests and gaps included); the TXT save state is unchanged." },
        { "无法导出，请查看顶部提示。", "Cannot export; see the notice above." },

        // ---------- 窗口内快捷键、数值校验与字号 ----------
        { "快捷键操作失败：", "Hotkey action failed: " },
        { "请稍候：当前正在演奏或读写曲谱，快捷键稍后可用。",
          "Please wait: playback or a score operation is running; the shortcut will work again shortly." },
        { "速度必须是 20～300 之间的整数（BPM）。", "Tempo must be an integer between 20 and 300 (BPM)." },
        { "音符间隔／留白必须是 10～5000 之间的整数（毫秒）。",
          "Note gap must be an integer between 10 and 5000 (milliseconds)." },
        { "谱面字号已调整为 {0:0.#}（Ctrl+滚轮缩放，Ctrl+0 复位）。",
          "Score font size set to {0:0.#} (Ctrl+wheel to zoom, Ctrl+0 to reset)." },
        { "请稍候：当前正在演奏或读写曲谱，稍后再拖入文件。",
          "Please wait: playback or a score operation is running; drop the file again shortly." },
        { "由 MIDI“{0}”转换，原 MIDI 未修改。请先试听检查，再保存 TXT 或游戏演奏。",
          "Converted from MIDI \"{0}\"; the original MIDI was not modified. Preview it first, then save the TXT or play it in game." },
        { "单旋律 MIDI 已导入为可编辑谱面，尚未保存 TXT。",
          "The single-line MIDI was imported as an editable score and has not been saved as TXT yet." },

        // ---------- MIDI 导入对话框 ----------
        { "导入到编辑器", "Import to editor" },
        { "选择单旋律轨道／通道。严格单音，不丢音、不截短、不自动移调。",
          "Choose one monophonic track/channel. Strictly single notes: nothing is dropped, shortened or transposed automatically." },
        { "固定 BPM", "Fixed BPM" },
        { "gap（ms）", "Gap (ms)" },
        { "整体移调（半音）", "Transpose (semitones)" },
        { "按原速度事件计算实际时间，转换为固定 BPM 下的自定义时值。gap 是目标谱面的留白，不从 MIDI 猜测；无法保留原起音、音尾与总时长时阻止导入。",
          "Real times come from the original tempo events and are converted to custom beat values at the fixed BPM. The gap is the target score's spacing and is never guessed from the MIDI; the import is blocked when the original note starts, ends and total length cannot be preserved." },
        { "使用建议移调", "Apply suggested transpose" },
        { "{0}\n音域：{1}～{2}；", "{0}\nRange: {1} – {2}; " },
        { "速度：", "Tempo: " },
        { "{0} 段速度", "{0} tempo segments" },
        { "建议整体移调 {0} 半音：原始音域覆盖率 {1}/{2}（{3}%）→ 建议移调后 {4}/{5}（{6}%）。仅供选择，未自动应用。",
          "Suggested transpose {0} semitone(s): original range coverage {1}/{2} ({3}%) → after transposing {4}/{5} ({6}%). It is only a suggestion and is not applied automatically." },
        { "\n当前移调 {0} 半音：{1}/{2} 音在支持范围内。",
          "\nWith the current transpose of {0} semitone(s): {1}/{2} notes are within range." },
        { "整体移调必须是整数半音。", "Transpose must be a whole number of semitones." },
        { "检查通过。音高、实际起音、发声结束和所选轨道总时长保留；未量化、未调整重叠。\n\n",
          "Check passed. Pitch, real note starts, note ends and the selected track's total length are preserved; nothing is quantized and no overlap is adjusted.\n\n" },
        { "\n（预览截断，导入时保留完整谱面）", "\n(preview truncated; the full score is kept on import)" },
        { "无法导入：共 {0} 项问题，未修改原 MIDI。\n",
          "Cannot import: {0} problem(s); the original MIDI was not modified.\n" },
        { "\n仅显示前 30 项，请先在原 MIDI 修正。",
          "\nOnly the first 30 items are shown; fix them in the original MIDI first." },

        // ---------- 系统对话框包装 ----------
        { "演奏已停止", "Playback stopped" },
        { "TXT 简谱|*.txt", "TXT score|*.txt" },
        { "标准 MIDI 文件|*.mid;*.midi", "Standard MIDI file|*.mid;*.midi" },
        { "标准 MIDI 文件|*.mid", "Standard MIDI file|*.mid" },
        { "曲谱、曲名、BPM或音符间隔已修改，是否保存？\n“否”放弃本次修改，“取消”返回编辑。",
          "The score, title, BPM or note gap has changed. Save it?\n\"No\" discards the changes, \"Cancel\" returns to editing." },
        { "曲谱尚未保存", "Score not saved" },

        // ---------- 保存、关闭与演奏状态 ----------
        { "正在停止演奏并关闭…", "Stopping playback and closing…" },
        { "正在等待演奏任务停止，窗口仍可响应…", "Waiting for the playback task to stop; the window is still responsive…" },
        { "演奏结束异常：", "Playback ended with an error: " },
        { "按键释放失败，请手动按下并松开相关键后再关闭：",
          "Some keys could not be released; press and release them manually, then close again: " },
        { "已取消关闭。", "Closing cancelled." },
        { "正在保存最后的设置，请稍候（窗口仍可响应）…", "Saving the final settings; the window is still responsive…" },
        { "关闭未完成，请重试：", "Close did not finish, please retry: " },
        { "正在读写曲谱，请完成后再关闭。", "A score operation is running; close again when it finishes." },
        { "设置会自动保存；每次启动默认游戏演奏模式，“仅测试”不勾选。",
          "Settings are saved automatically; every start defaults to game performance mode with \"Test only\" unchecked." },
        { "部分数值尚未填写完整，保留上次有效设置。", "Some numbers are incomplete, so the last valid settings were kept." },
        { "设置未保存：", "Settings not saved: " },
        { "设置已保存（快捷键、速度、音符间隔和试听音量）。",
          "Settings saved (hotkeys, tempo, note gap and preview volume)." },
        { "等待松开快捷键超时，已取消演奏。", "Timed out waiting for the hotkey to be released; playback was cancelled." },
        { "请松开启动键及 Ctrl / Alt / Shift / Win；{0} 可停止。",
          "Release the start key and Ctrl / Alt / Shift / Win; press {0} to stop." },
        { "停止键 {0} 不可用，禁止真实演奏。请点击“自定义快捷键”或“重试注册”。",
          "The stop key {0} is unavailable, so real performance is blocked. Click \"Custom hotkeys\" or \"Retry registration\"." },
        { "曲谱操作失败：", "Score operation failed: " },
        { "已导入，检查通过；请确认速度（BPM）。", "Imported and checked; please confirm the tempo (BPM)." },
        { "已导入，请修正顶部提示的错误。", "Imported; fix the errors shown above." },
        { "曲谱已保存（新格式，含曲名、BPM和音符间隔）。",
          "Score saved (new format with title, BPM and note gap)." },
        { "曲谱未保存：", "Score not saved: " },
        { "正在停止试听…", "Stopping preview…" },
        { "正在停止并释放输入…", "Stopping and releasing input…" },
        { "已停止。", "Stopped." },
        { "释放按键失败：", "Failed to release keys: " },
        { "已停止：", "Stopped: " },
        { " 释放失败，请手动按下并松开相关键：", " · release failed, press and release those keys manually: " },
        { "无法开始，请查看顶部提示。", "Cannot start; see the notice above." },
        { "共{0}个音/休止，{1}拍，预计{2}秒（不含倒计时）\n",
          "{0} notes/rests, {1} beats, about {2}s (countdown excluded)\n" },
        { "{0}s  {1}  {2}拍  ({3}ms)", "{0}s  {1}  {2} beats  ({3}ms)" },
        { "谱面／设置错误：", "Score / settings error: " },
        { "测试完成：未操作游戏，也未发声。需要游戏演奏请取消“仅测试”。",
          "Test finished: no game input and no sound. Uncheck \"Test only\" for game performance." },
        { "演奏完成。", "Performance finished." },
        { "{0}：{1}秒后开始，请切到目标窗口…", "{0}: starting in {1}s, switch to the target window…" },
        { "倒计时结束时仍在播放器窗口，已取消。请在3秒倒计时内切到游戏口琴界面，或在游戏内按开始快捷键。",
          "The countdown ended while HarpKit was still the active window, so playback was cancelled. Switch to the in-game harmonica view within the 3-second countdown, or press the start hotkey while the game is active." },
        { "目标窗口失去焦点，已停止。演奏期间请勿切换窗口；切回游戏后重新开始。",
          "The target window lost focus, so playback stopped. Do not switch windows while playing; switch back to the game and start again." },
        { "常见原因：其他播放器、录屏或键盘工具占用了热键。点击“自定义快捷键”换一个组合，或关闭占用程序后点“重试注册”。管理员权限不能解除热键占用。",
          "Common cause: another player, screen recorder or keyboard tool already owns the hotkey. Click \"Custom hotkeys\" to pick another combination, or close the other program and click \"Retry registration\". Administrator rights cannot break a hotkey conflict." },
        { "{0}/{1} 个音", "{0}/{1} notes" },
        { "{0}/{1}：{2} / {3}拍", "{0}/{1}: {2} / {3} beats" },
        { "{0}ms  {1}  {2}拍 ({3}ms)\n", "{0}ms  {1}  {2} beats ({3}ms)\n" },

        // ---------- 快捷键对话框 ----------
        { "点击录入框后按下快捷键，或用下拉框和勾选项设置。\n修改期间暂停全局快捷键，关闭此窗口后重新注册。",
          "Click the capture box and press a key, or use the drop-down and check boxes.\nGlobal hotkeys pause while editing and are re-registered when this dialog closes." },
        { "开始快捷键", "Start hotkey" },
        { "停止快捷键", "Stop hotkey" },
        { "停止建议使用容易按到的单键。F12、Win组合及演奏键Z/X/C/V/B/N/M/逗号不支持。",
          "Use an easy-to-reach single key for Stop. F12, Win combinations and the performance keys Z/X/C/V/B/N/M/comma are not supported." },
        { "恢复 F6 / F8", "Restore F6 / F8" },
        { "应用并检查占用", "Apply and check conflicts" },
        { "现在按下快捷键；如被其他软件拦截，可使用下方选项。",
          "Press the hotkey now; if another program intercepts it, use the options below." },
        { "已录入，点击“应用并检查占用”生效。", "Captured; click \"Apply and check conflicts\" to use it." },

        // ---------- 数值校验 ----------
        { "速度（BPM）范围20～300，请输入整数。", "Tempo (BPM) must be an integer between 20 and 300." },
        { "音符间隔／留白须为10～5000毫秒的整数。", "Note gap must be an integer between 10 and 5000 ms." },
        { "每拍时长无效。", "Invalid beat duration." },
        { "第{0}个字符的音过短：扣除{1}ms准备和{2}ms留白后不足40ms。请降低BPM或减小音符间隔。",
          "The note at character {0} is too short: after {1} ms preparation and {2} ms gap less than 40 ms remains. Lower the BPM or reduce the note gap." },

        // ---------- 单实例 ----------
        { "播放器已经运行，请在任务栏中打开已有窗口。", "HarpKit is already running; open the existing window from the taskbar." },

        // ---------- 快捷键校验（HotkeyBinding / HotkeyController） ----------
        { "仅支持 Ctrl、Alt、Shift，不支持 Windows 键。", "Only Ctrl, Alt and Shift are supported; the Windows key is not." },
        { "F12为系统调试保留键，请选择其他键。", "F12 is reserved for system debugging; choose another key." },
        { "Z/X/C/V/B/N/M/逗号用于演奏，请选择其他快捷键（包括组合键）。",
          "Z/X/C/V/B/N/M/comma are used for playing; choose another hotkey (combinations included)." },
        { "请选择 F1～F11、字母、数字或导航键。", "Choose F1–F11, a letter, a digit or a navigation key." },
        { "字母、数字和空格须搭配 Ctrl、Alt 或 Shift，避免影响日常输入。",
          "Letters, digits and Space need Ctrl, Alt or Shift so normal typing is not affected." },
        { "Ctrl+Alt+Delete为系统保留组合。", "Ctrl+Alt+Delete is reserved by Windows." },
        { "Alt+F4用于关闭窗口，请选择其他组合。", "Alt+F4 closes windows; choose another combination." },
        { "带 Ctrl 或 Alt 的 Esc 为系统快捷键，请选择其他组合。", "Esc with Ctrl or Alt is a system shortcut; choose another combination." },
        { "Alt+Space用于系统菜单，请选择其他组合。", "Alt+Space opens the system menu; choose another combination." },
        { "开始键：", "Start key: " },
        { "停止键：", "Stop key: " },
        { "开始键和停止键不能相同。", "The start key and the stop key must differ." },
        { "未注册", "Not registered" },
        { "快捷键可用", "Hotkey available" },
        { "快捷键被其他程序占用", "Hotkey taken by another program" },
        { "注册失败（错误码{0}）", "Registration failed (error {0})" },
        { "曲谱库快捷键编号无效。", "Invalid library hotkey id." },
        { "曲谱库快捷键 {0} 无效：{1}", "Library hotkey {0} is invalid: {1}" },
        { "快捷键 {0} 重复，无法同时注册。", "Hotkey {0} is duplicated and cannot be registered twice." },
        { "开始 {0}：{1}；停止 {2}：{3}。", "Start {0}: {1}; stop {2}: {3}." },
        { "停止键不可用，禁止真实演奏；请修改快捷键或解除占用后点“重试注册”。",
          "The stop key is unavailable, so real performance is blocked; change the hotkey or free it and click \"Retry registration\"." },
        { "可点击“开始”按钮演奏；也可修改开始键或重试注册。",
          "You can start with the Start button, or change the start key and retry registration." },
        { "快捷键已就绪。", "Hotkeys are ready." },
        { "可用", "available" },
        { "被占用", "taken" },
        { "注册失败（错误码{0}，可能被其他程序占用）", "registration failed (error {0}, another program may own it)" },

        // ---------- 曲谱库数据校验 ----------
        { "曲谱“{0}”的快捷键无效：{1}", "The hotkey of \"{0}\" is invalid: {1}" },
        { "曲谱库条目缺少有效的文件路径。", "A score library entry has no valid file path." },
        { "曲谱库必须使用完整路径：{0}", "The score library requires an absolute path: {0}" },
        { "曲谱“{0}”的曲名不能超过{1}个字符，也不能包含控制字符。",
          "The title of \"{0}\" must not exceed {1} characters or contain control characters." },
        { "曲谱库最多保存{0}条曲谱。", "The score library can hold at most {0} scores." },
        { "曲谱库包含空条目。", "The score library contains an empty entry." },
        { "曲谱“{0}”的快捷键 {1} 与开始/停止键相同，请重新绑定。",
          "The hotkey {1} of \"{0}\" equals the start/stop key; bind it again." },
        { "快捷键 {0} 被多首曲谱使用，请只保留一个绑定。",
          "Hotkey {0} is used by more than one score; keep a single binding." },
        { "与开始键 {0} 相同，请选择其他组合。", "It equals the start key {0}; choose another combination." },
        { "与停止键 {0} 相同，请选择其他组合。", "It equals the stop key {0}; choose another combination." },
        { "与曲谱“{0}”的快捷键重复。", "It duplicates the hotkey of \"{0}\"." },
        { "忽略{0}条无效条目", "{0} invalid entry/entries ignored" },
        { "清除{0}个无效或冲突的快捷键", "{0} invalid or conflicting hotkey(s) cleared" },
        { "曲谱库数据有问题，已自动清理（{0}）。", "The score library data was invalid and has been cleaned up ({0})." },
        { "，", ", " },

        // ---------- 设置读取与校验 ----------
        { "缺少快捷键设置。", "The hotkey settings are missing." },
        { "设置数值超出允许范围。", "A setting value is outside the allowed range." },
        { "窗口宽度设置超出允许范围。", "The saved window width is outside the allowed range." },
        { "窗口高度设置超出允许范围。", "The saved window height is outside the allowed range." },
        { "窗口横向位置设置超出允许范围。", "The saved window position (X) is outside the allowed range." },
        { "窗口纵向位置设置超出允许范围。", "The saved window position (Y) is outside the allowed range." },
        { "设置文件为空。", "The settings file is empty." },
        { "曲谱库设置无效，已忽略曲谱库。", "The score library settings were invalid and have been ignored. " },
        { "其他设置未受影响（{0}）。", "Other settings are unaffected ({0})." },
        { "无法读取原设置，已使用默认值：", "The saved settings could not be read, defaults are used: " },
    };
}
